### ISSUE TITLE
GIFs and "Invalid data when processing input"

### ISSUE THREAD

**Issue by nyov** [mikeboers/PyAV#132]
This may be a user issue, but I can't seem to figure out how to work with (animated) gif files.
Is there a way to work with files that have no frame counts?

Also, using the basic demo code, I get this on any gif I tested
```py
import av

container = av.open('/tmp/some.gif')
video = next(s for s in container.streams if s.type == b'video')

for packet in container.demux(video):
    for frame in packet.decode():
        frame.to_image().save('/tmp/frame-%04d.jpg' % frame.index)
```
```sh
$ python demo.py 
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    for frame in packet.decode():
  File "av/packet.pyx", line 30, in av.packet.Packet.decode (src/av/packet.c:1372)
  File "av/stream.pyx", line 203, in av.stream.Stream.decode (src/av/stream.c:4021)
  File "av/video/stream.pyx", line 51, in av.video.stream.VideoStream._decode_one (src/av/video/stream.c:1680)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1380)
av.AVError: [Errno 1052488119] Invalid data found when processing input
```

Is that reproducible or an issue with my local installation?

**Comment by nyov** [comment]
No info here? Is nobody working with gifs? Trying to seek in gifs fails like this:

```pytb
Traceback (most recent call last):
  [snip]
  File "avconv.py", line 190, in get_frame
    stream.seek(seek_pts)
  File "av/stream.pyx", line 232, in av.stream.Stream.seek (src/av/stream.c:4397)
  File "av/container.pyx", line 169, in av.container.ContainerProxy.seek (src/av/container.c:3284)
  File "av/utils.pyx", line 32, in av.utils.err_check (src/av/utils.c:1012)
av.AVError: [Errno 22] Invalid argument
```

**Comment by TechWhizZ199** [comment]
Hi @nyov , the issue here is that the GIF is not a video/audio file, so it does not have a stream. The library is yet to be exposed to working with just a single frame - encoding/decoding a single video/audio frame. If/when this has been exposed, we should be able to handle images and create a video frame from an image format.

Tech

**Comment by mikeboers** [comment]
@TechWhizZ199: I'm pretty sure that ffmpeg abstracts it into a `"gif"` container format and a `"gif"` stream. From `ffprobe`:

```
Input #0, gif, from '/Users/mikeboers/Desktop/test.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, bgra, 540x540, 15.08 fps, 15 tbr, 100 tbn, 100 tbc
```

So... yeah. PyAV already does do some stuff with GIFs. I get a ton of `"Invalid argument"` errors myself whenever I try to do GIF stuff, but it does some things. E.g.:

```
$ python examples/decode.py /Users/mikeboers/Desktop/test.gif 
container: <av.InputContainer '/Users/mikeboers/Desktop/test.gif'>
	format: <av.ContainerFormat 'gif'>
	duration: -9.22337203685e+12
	metadata:

1 stream(s):
	<av.VideoStream #0 gif, bgra 540x540 at 0x108042a50>
		time_base: Fraction(1, 100)
		rate: Fraction(1, 100)
		start_time: -9223372036854775808
		duration: None
		bit_rate: None
		bit_rate_tolerance: 4000000
		video:
			format: <av.VideoFormat bgra, 540x540>
			average_rate: Fraction(181, 12)
		metadata:

00 <av.Packet of #0, dts=0, pts=0 at 0x109a44180>
	duration: 0.070s (7/100 or 7/100)
	pts: 0.000s (0 or 0/100)
	dts: 0.000s (0 or 0/100)
	decoded: <av.VideoFrame #0, bgra 540x540 at 0x109a40600>
		pts: 0.000s (0 or 0/100)
```

That being said, @nyov, I don't have insight into your specific problem. [Upload some sample GIFs you are having trouble](https://www.dropbox.com/request/T9C5Uts7tsQuwo7sifPP) with so I can poke it if I find some time (but, as you can tell, I'm not able to put tons of time into this project all the time).

**Comment by nyov** [comment]
Thank you for the replies.
@mikeboers, actually I haven't found a gif (animated) which worked for me, thus I didn't specify any particular file(s).
But I have tested mostly with imgur.com images, so perhaps it's particular to their encoding software. (Here is a random one: https://i.imgur.com/oNdLHXB.gif )

**Comment by mikeboers** [comment]
What do you mean by "worked"? Here is output from one of the examples:

```
$ python examples/decode.py oNdLHXB.gif 
container: <av.InputContainer 'oNdLHXB.gif'>
	format: <av.ContainerFormat 'gif'>
	duration: -9.22337203685e+12
	metadata:

1 stream(s):
	<av.VideoStream #0 gif, bgra 500x500 at 0x107d11e10>
		time_base: Fraction(1, 100)
		rate: Fraction(1, 100)
		start_time: -9223372036854775808
		duration: None
		bit_rate: None
		bit_rate_tolerance: 4000000
		video:
			format: <av.VideoFormat bgra, 500x500>
			average_rate: Fraction(25, 1)
		metadata:

00 <av.Packet of #0, dts=0, pts=0 at 0x1094e83e0>
	duration: 0.040s (1/25 or 4/100)
	pts: 0.000s (0 or 0/100)
	dts: 0.000s (0 or 0/100)
	decoded: <av.VideoFrame #0, bgra 500x500 at 0x109511360>
		pts: 0.000s (0 or 0/100)
```

And the `save_frames.py` extracts frames like this:

![0000](https://cloud.githubusercontent.com/assets/130470/16389425/e6481cb6-3c6b-11e6-8a8d-a8ff0b9ff9ca.jpg)

**Comment by mikeboers** [comment]
You mean seeking.

**Comment by mikeboers** [comment]
I can call the seek methods without errors, but I don't think it is going to seek. Trying to do the same with ffmpeg:

```
$ ffmpeg -y -loglevel verbose -noaccurate_seek -i oNdLHXB.gif -ss 0.5 test.gif
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.0 (clang-700.0.72)
  configuration: --disable-static --enable-shared --disable-doc --prefix=/Users/mikeboers/Documents/PyAV/venvs/Darwin.14.5.0.cpython2.7/vendor/ffmpeg-3.0
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
Input #0, gif, from 'oNdLHXB.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, 1 reference frame, bgra, 500x500, 25 fps, 25 tbr, 100 tbn, 100 tbc
[graph 0 input from stream 0:0 @ 0x7ff0c1c21ce0] w:500 h:500 pixfmt:bgra tb:1/100 fr:25/1 sar:0/1 sws_param:flags=2
[auto-inserted scaler 0 @ 0x7ff0c1d00400] w:iw h:ih flags:'bicubic' interl:0
[format @ 0x7ff0c1c222c0] auto-inserting filter 'auto-inserted scaler 0' between the filter 'Parsed_null_0' and the filter 'format'
[auto-inserted scaler 0 @ 0x7ff0c1d00400] w:500 h:500 fmt:bgra sar:0/1 -> w:500 h:500 fmt:bgr8 sar:0/1 flags:0x4
Output #0, gif, to 'test.gif':
  Metadata:
    encoder         : Lavf57.25.100
    Stream #0:0: Video: gif, 1 reference frame, bgr8, 500x500, q=2-31, 200 kb/s, 25 fps, 100 tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.24.102 gif
Stream mapping:
  Stream #0:0 -> #0:0 (gif (native) -> gif (native))
Press [q] to stop, [?] for help
No more output streams to write to, finishing.
frame=   12 fps=0.0 q=-0.0 Lsize=    1300kB time=00:00:00.52 bitrate=20483.0kbits/s speed=2.27x    
video:1299kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.067418%
Input file #0 (oNdLHXB.gif):
  Input stream #0:0 (video): 25 packets read (2488589 bytes); 25 frames decoded; 
  Total: 25 packets (2488589 bytes) demuxed
Output file #0 (test.gif):
  Output stream #0:0 (video): 12 frames encoded; 12 packets muxed (1330500 bytes); 
  Total: 12 packets (1330500 bytes) muxed

```

You can see how it decodes 25 frames, and only encodes 12. I don't think ffmpeg is able to seek within GIFs. Therefore, PyAV can't either.

Unless there is something I'm not following, this is an ffmpeg "problem".

**Comment by nyov** [comment]
Okay, so this is some kind of ffmpeg strangeness. Thanks for the help!

Looks like my version picks a wrong container format or something.
For the record, my output looks like this:
```
$ python examples/decode.py oNdLHXB.gif 
container: <av.InputContainer 'oNdLHXB.gif'>
	format: <av.ContainerFormat 'image2'>
	duration: 0.04
	metadata:

1 stream(s):
	<av.VideoStream #0 gif, pal8 500x500 at 0x7f99b0bfd230>
		time_base: Fraction(1, 25)
		rate: Fraction(0, 1)
		start_time: 0
		duration: 0.040s (1/25 or 1/25)
		bit_rate: None
		bit_rate_tolerance: 4000000
		video:
			format: <av.VideoFormat pal8, 500x500>
			average_rate: Fraction(0, 1)
		metadata:

00 <av.Packet of #0, dts=0, pts=0 at 0x7f99b0c59348>
	duration: 0.040s (1/25 or 1/25)
	pts: 0.000s (0 or 0/25)
	dts: 0.000s (0 or 0/25)
Traceback (most recent call last):
  File "examples/decode.py", line 92, in <module>
    for frame in packet.decode():
  File "av/packet.pyx", line 30, in av.packet.Packet.decode (src/av/packet.c:1310)
    return self.stream.decode(self, count)
  File "av/stream.pyx", line 203, in av.stream.Stream.decode (src/av/stream.c:4048)
    decoded = self._decode_one(&packet.struct, &data_consumed)
  File "av/video/stream.pyx", line 51, in av.video.stream.VideoStream._decode_one (src/av/video/stream.c:1716)
    data_consumed[0] = err_check(result)
  File "av/utils.pyx", line 32, in av.utils.err_check (src/av/utils.c:1012)
    cdef int stash_exception(exc_info=None):
av.AVError: [Errno 1052488119] Invalid data found when processing input
```

**Comment by mikeboers** [comment]
That does not seem right at all. Can you tell me what version you are using (with `python -m av --version`)?

**Comment by nyov** [comment]
It was a problem with outdated development header-files. Needed to recompile pyav against the updated headers.

Here's the old, problematic lib versions.
```
$ python -m av --version
PyAV v0.3.1
git origin: git@github.com:mikeboers/PyAV
git commit: unknown-commit
library configuration: --arch=amd64 --enable-pthreads --enable-runtime-cpudetect --extra-version='6:11.7-1~deb8u1' --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --disable-avserver --disable-protocol=concat --enable-bzlib --enable-libdc1394 --enable-libfreetype --enable-frei0r --enable-gnutls --enable-libgsm --enable-libmp3lame --enable-librtmp --enable-libopencv --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvpx --enable-zlib --enable-gpl --enable-swscale --enable-libcdio --enable-x11grab --enable-libx264 --enable-libxvid --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-static
library license: GPL version 2 or later
libavdevice    55.  0.  0
libavformat    56.  1.  0
libavresample   2.  1.  0
libavutil      54.  3.  0
libswscale      3.  0.  0
library configuration: --arch=amd64 --enable-pthreads --enable-runtime-cpudetect --extra-version='6:11.7-1~deb8u1' --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --disable-avserver --disable-protocol=concat --enable-bzlib --enable-libdc1394 --enable-libfreetype --enable-frei0r --enable-gnutls --enable-libgsm --enable-libmp3lame --enable-librtmp --enable-libopencv --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvpx --enable-zlib --enable-gpl --enable-swscale --enable-libcdio --enable-x11grab --enable-libx264 --enable-libxvid --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-static --enable-libopencore-amrnb --enable-version3 --enable-libopencore-amrwb --enable-version3 --enable-libvo-aacenc --enable-version3 --enable-libvo-amrwbenc --enable-version3
library license: GPL version 3 or later
libavcodec     56.  1.  0
```

After reinstalling/recompiling PyAV, it works:
```
$ python -m av --version
PyAV v0.3.1
git origin: git@github.com:mikeboers/PyAV
git commit: unknown-commit
library configuration: --prefix=/usr --extra-version='2~bpo8+1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
library license: GPL version 2 or later
libavdevice    57.  0.101
libavformat    57. 25.100
libavutil      55. 17.103
libswresample   2.  0.101
libswscale      4.  0.100
library configuration: --prefix=/usr --extra-version='2~bpo8+1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_amrwbenc
library license: GPL version 3 or later
libavcodec     57. 24.102
```

```
$ ffmpeg -version
ffmpeg version 3.0.2-2~bpo8+1 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.9.2 (Debian 4.9.2-10)
configuration: --prefix=/usr --extra-version='2~bpo8+1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100
```

**Comment by nyov** [comment]
If I remember correctly, I had pyav installed from a deb package, so I built it from the git source.

The commands are `build` and `install` from setup.py.
Try `python setup.py --help install` (in your git tree).

I used a user-local install (the date of the files still matched this issue, heh).
That is: `python setup.py clean && python setup.py install --user`, which builds and installs pyav into `~/.local/lib/python2.7/site-packages/av` (or as an av*.egg). But you may prefer using a virtualenv instead.

You may need ffmpeg development headers installed for this (libav*-dev packages in debian, specifically some or all of `libavcodec-dev`, `libavdevice-dev`, `libavfilter-dev`, `libavformat-dev`, `libavresample-dev`).

Hope this helps.

**Comment by nyov** [comment]
FWIW this new build from current master now, doesn't seem to work for me anymore, because
```
Traceback (most recent call last):
  File "./video2image.py", line 460, in <module>
    some_test()
  File "./video2image.py", line 200, in some_test
    import av # PyAV
  File "/tmp/pyav.git/av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "/tmp/pyav.git/av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame (src/av/audio/frame.c:2741)
    from av.audio.format cimport get_audio_format
  File "av/container/streams.pxd", line 4, in init av.frame (src/av/frame.c:2773)
    cdef class StreamContainer(object):
  File "/tmp/pyav.git/av/container/__init__.py", line 1, in <module>
    from .core import Container, open
  File "av/packet.pxd", line 7, in init av.container.core (src/av/container/core.c:5406)
    
  File "av/container/streams.pxd", line 4, in init av.packet (src/av/packet.c:2555)
    cdef class StreamContainer(object):
  File "av/stream.pxd", line 10, in init av.container.streams (src/av/container/streams.c:2741)
    
  File "av/audio/frame.pxd", line 10, in init av.stream (src/av/stream.c:5485)
    cdef class AudioFrame(Frame):
AttributeError: 'module' object has no attribute 'AudioFrame'
```
but oh well. Maybe you won't have that issue.

**Comment by mikesalmonuk** [comment]
Thanks very much @nyov - appreciate your response, will have a look at what you've said there and see if that works for me. Cheers!
