### ISSUE TITLE
Expose encoding/decoding raw packets without streams

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#155]
Streams are not actually necessary for encoding/decoding, only muxing/demuxing. Refactor encoding/decoding onto a `CodecContext`, and then have a `{Video,Audio,Subtitle}CodecContext` which implements the specifics functions. 

Do this for #154.

**Comment by TechWhizZ199** [comment]
I was tried making some edits to the FFVideo library, though due to the fact that we do not have #174 solved, I can't actually proceed any further. I thought maybe I could load a sample flv file into the library , this would mean the library would set the codec context to flv. Then I can just feed in custom packets by creating a new function which should theoretically decode the packets. 

I have yet to try this out but the library I am modifying resides here: https://github.com/oddballz/labs/tree/master/AV

**Comment by TechWhizZ199** [comment]
Just a quick follow up for #174 we need to have access to:

1. avcodec_find_decoder() with the CODEC IDS e.g. AV_CODEC_ID_MPEG1VIDEO
2. avcodec_alloc_context from which we can just use avcodec_open to open and start using the codec.

**Comment by mikeboers** [comment]
I've started making progress in the `codec-ctx` branch. Encoding works (with a ton of hardcoded options), but decoding roughly does this (lifting the error from #181):

```
<av.VideoCodecContext video/flv at 0x7f470d5f47e0>
<av.Packet of #0, dts=None, pts=None; 128 bytes at 0x7f4711bd3890>
Traceback (most recent call last):
  File "/home/ubuntu/workspace/PyAV/scratchpad/cctx_decode.py", line 30, in <module>
    frames = cc.decode(packet) or ()
  File "av/codeccontext.pyx", line 83, in av.codeccontext.CodecContext.decode (src/av/codeccontext.c:3598)
  File "av/codeccontext.pyx", line 115, in av.codeccontext.CodecContext.decode (src/av/codeccontext.c:3331)
  File "av/video/codeccontext.pyx", line 134, in av.video.codeccontext.VideoCodecContext._decode_one (src/av/video/codeccontext.c:2109)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1517)
av.AVError: [Errno 1094995529] Invalid data found when processing input
ERROR:libav.flv:Bad picture start code
ERROR:libav.flv:header damaged
```

I got the same in my "mpeg4" tests. More testing/investigation is needed.

**Comment by GoelBiju** [comment]
I'm not sure if what I am saying is correct, but when allocating the packet with the data, maybe we should provide with the compressed data and not just a chunk of the file. E.g. when we are streaming, we get the frames of the data. If this is the case, is it only looking to decode the actual frame in the data? 

Maybe treating the the file without streams causes this, is it only useful for raw packet data?

**Comment by GoelBiju** [comment]
I just saw the reference to exactly what you meant here: https://ffmpeg.org/doxygen/trunk/doc_2examples_2decoding_encoding_8c-example.html

See note the note under the video_decode function. 

It says:

```c
 if(codec->capabilities&CODEC_CAP_TRUNCATED)
        c->flags|= CODEC_FLAG_TRUNCATED; /* we do not send complete frames */
    /* For some codecs, such as msmpeg4 and mpeg4, width and height
       MUST be initialized there because this information is not
       available in the bitstream. */
    /* open it */
    if (avcodec_open2(c, codec, NULL) < 0) {
        fprintf(stderr, "Could not open codec\n");
        exit(1);
    }
    f = fopen(filename, "rb");
    if (!f) {
        fprintf(stderr, "Could not open %s\n", filename);
        exit(1);
    }
    frame = av_frame_alloc();
    if (!frame) {
        fprintf(stderr, "Could not allocate video frame\n");
        exit(1);
    }
    frame_count = 0;
    for (;;) {
        avpkt.size = fread(inbuf, 1, INBUF_SIZE, f);
        if (avpkt.size == 0)
            break;
        /* NOTE1: some codecs are stream based (mpegvideo, mpegaudio)
           and this is the only method to use them because you cannot
           know the compressed data size before analysing it.
           BUT some other codecs (msmpeg4, mpeg4) are inherently frame
           based, so you must call them with all the data for one
           frame exactly. You must also initialize 'width' and
           'height' before initializing them. */
        /* NOTE2: some codecs allow the raw parameters (frame size,
           sample rate) to be changed at any frame. We handle this, so
           you should also take care of it */
        /* here, we use a stream based decoder (mpeg1video), so we
           feed decoder and see if it could decode a frame */
        avpkt.data = inbuf;
        while (avpkt.size > 0)
            if (decode_write_frame(outfilename, c, frame, &frame_count, &avpkt, 0) < 0)
                exit(1);
    }
    /* some codecs, such as MPEG, transmit the I and P frame with a
       latency of one frame. You must do the following to have a
       chance to get the last frame of the video */
    avpkt.data = NULL;
    avpkt.size = 0;
    decode_write_frame(outfilename, c, frame, &frame_count, &avpkt, 1);
```

**Comment by mikeboers** [comment]
Just pushed another commit. With big enough chunks it is able to decode from mp4 and flv. I think a problem we are running into is that `Packet`s don't mutate as they are consumed to reflect how much data is left, and so for stuff like `flv` that does not need a parser we are dropping parts of frames across packet boundaries.

Getting somewhere though!

**Comment by GoelBiju** [comment]
Great work @mikeboers , I really look forward to seeing this library have an option to decode a single frame from a packet (and encode a frame from raw data)!

**Comment by GoelBiju** [comment]
I was trying to build the latest commit on virtualbox and I seem to be encountering some issues without cythonizing the .pyx files. The previous set of files before the AVCodec context parser commit was working fine.

```terminal
goel@goel-VirtualBox:~/Desktop/PyAV$ sudo python setup.py build_ext --inplace
running build_ext
running reflect
running config
looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing
writing build/temp.linux-x86_64-2.7/include/pyav/config.h
running cythonize
Compiling av/utils.pyx because it changed.
[1/1] Cythonizing av/utils.pyx
Compiling av/packet.pyx because it changed.
[1/1] Cythonizing av/packet.pyx
warning: av/packet.pyx:56:13: Unreachable code
Compiling av/descriptor.pyx because it changed.
[1/1] Cythonizing av/descriptor.pyx
Compiling av/bytesource.pyx because it changed.
[1/1] Cythonizing av/bytesource.pyx
Compiling av/_core.pyx because it changed.
[1/1] Cythonizing av/_core.pyx
Compiling av/buffer.pyx because it changed.
[1/1] Cythonizing av/buffer.pyx
Compiling av/stream.pyx because it changed.
[1/1] Cythonizing av/stream.pyx
Compiling av/dictionary.pyx because it changed.
[1/1] Cythonizing av/dictionary.pyx
Compiling av/frame.pyx because it changed.
[1/1] Cythonizing av/frame.pyx
Compiling av/logging.pyx because it changed.
[1/1] Cythonizing av/logging.pyx
Compiling av/plane.pyx because it changed.
[1/1] Cythonizing av/plane.pyx
Compiling av/format.pyx because it changed.
[1/1] Cythonizing av/format.pyx
Compiling av/option.pyx because it changed.
[1/1] Cythonizing av/option.pyx
Compiling av/subtitles/stream.pyx because it changed.
[1/1] Cythonizing av/subtitles/stream.pyx
Compiling av/subtitles/subtitle.pyx because it changed.
[1/1] Cythonizing av/subtitles/subtitle.pyx
Compiling av/audio/layout.pyx because it changed.
[1/1] Cythonizing av/audio/layout.pyx
Compiling av/audio/resampler.pyx because it changed.
[1/1] Cythonizing av/audio/resampler.pyx
Compiling av/audio/stream.pyx because it changed.
[1/1] Cythonizing av/audio/stream.pyx
Compiling av/audio/fifo.pyx because it changed.
[1/1] Cythonizing av/audio/fifo.pyx
Compiling av/audio/frame.pyx because it changed.
[1/1] Cythonizing av/audio/frame.pyx
Compiling av/audio/plane.pyx because it changed.
[1/1] Cythonizing av/audio/plane.pyx
Compiling av/audio/format.pyx because it changed.
[1/1] Cythonizing av/audio/format.pyx
av/codec/context.pyx: cannot find cimported module 'av.codec.codec'
av/codec/context.pxd: cannot find cimported module 'av.codec.codec'
/home/goel/Desktop/PyAV/av/codec/context.pxd: cannot find cimported module 'av.codec.codec'
Compiling av/codec/context.pyx because it changed.
[1/1] Cythonizing av/codec/context.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int64_t

cimport libav as lib

from av.codec.codec cimport Codec
^
------------------------------------------------------------

av/codec/context.pxd:5:0: 'av/codec/codec.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int64_t

cimport libav as lib

from av.codec.codec cimport Codec
^
------------------------------------------------------------

av/codec/context.pxd:5:0: 'av/codec/codec/Codec.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    cdef size_t parse_buffer_max_size
    cdef size_t parse_pos

    cdef _init(self, lib.AVCodecContext *ptr)

    cdef readonly Codec codec
                 ^
------------------------------------------------------------

av/codec/context.pxd:22:18: 'Codec' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cdef size_t parse_buffer_max_size
    cdef size_t parse_pos

    cdef _init(self, lib.AVCodecContext *ptr)

    cdef readonly Codec codec
                       ^
------------------------------------------------------------

av/codec/context.pxd:22:24: C attribute of type '<error>' cannot be accessed from Python

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdlib cimport malloc, realloc, free
from cpython cimport PyWeakref_NewRef

cimport libav as lib

from av.codec.codec cimport Codec, wrap_codec
^
------------------------------------------------------------

av/codec/context.pyx:8:0: 'av/codec/codec/wrap_codec.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

cdef class CodecContext(object):
    
    @staticmethod
    def create(codec, mode=None):
        cdef Codec cy_codec = codec if isinstance(codec, Codec) else Codec(codec, mode)
            ^
------------------------------------------------------------

av/codec/context.pyx:38:13: 'Codec' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
cdef class CodecContext(object):
    
    @staticmethod
    def create(codec, mode=None):
        cdef Codec cy_codec = codec if isinstance(codec, Codec) else Codec(codec, mode)
        cdef lib.AVCodecContext *c_ctx = lib.avcodec_alloc_context3(cy_codec.ptr)
                                                                           ^
------------------------------------------------------------

av/codec/context.pyx:39:76: Cannot convert Python object to 'AVCodec *'

Error compiling Cython file:
------------------------------------------------------------
...
        if sentinel is not _cinit_sentinel:
            raise RuntimeError('cannot instantiate CodecContext')

    cdef _init(self, lib.AVCodecContext *ptr):
        self.ptr = ptr
        self.codec = wrap_codec(self.ptr.codec)
                                       ^
------------------------------------------------------------

av/codec/context.pyx:48:40: Cannot convert 'AVCodec *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        # We might pass partial frames.
        if self.codec.ptr.capabilities & lib.CODEC_CAP_TRUNCATED:
            self.ptr.flags |= lib.CODEC_FLAG_TRUNCATED

        # TODO: Options
        err_check(lib.avcodec_open2(self.ptr, self.codec.ptr, NULL))
                                                       ^
------------------------------------------------------------

av/codec/context.pyx:66:56: Cannot convert Python object to 'AVCodec *'
Traceback (most recent call last):
  File "setup.py", line 715, in <module>
    distclass=distclass,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 657, in run
    self.run_command('cythonize')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 575, in run
    include_path=ext.include_dirs,
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1037, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: av/codec/context.pyx
```

**Comment by tuxuser** [comment]
Hello people,
Is the implementation finished.. And if so, is there a quick example available? Thank you

**Comment by GoelBiju** [comment]
Hi @tuxuser , I was wondering how you managed to use CodecContext. Is there an example I could see please?

Thank you.

**Comment by tuxuser** [comment]
Sure, here is a snippet that works for me
```python
import av

data = b'\xDE\xAD\xBE\xEF'  # Just for illustration 
codec_ctx = av.codec.CodecContext.create('aac', 'r')
packet = av.packet.Packet(data)
for frame in codec_ctx.decode(packet):
    decoded_data = frame.planes[0].to_bytes()
    # Do stuff
```

The original 'scratch'-code: https://github.com/mikeboers/PyAV/blob/master/scratchpad/cctx_decode.py
Did not work for me as **CodecContext.parse** expects a string... but I wanted to supply binary data of course... That's why I am assembling the **av.packet.Packet** by myself

**Comment by GoelBiju** [comment]
Thanks for the help @tuxuser , my issue was similarly like this, I had some h263 RTMP data which I needed to create an flv file from, so I needed a way to decode that data and place it into the file.

**Comment by mikeboers** [comment]
@tuxuser Thanks for the example, and noting that the `parse` doesn't work well for you. That was in the first iteration of the `CodecContext` refactor, and I haven't revisited it since.

**Comment by adavoudi** [comment]
@koenvo Did you manage to solve the problem?
In my case the error is as below:

`
File "av/codec/context.pyx", line 326, in av.codec.context.CodecContext.decode
  File "av/codec/context.pyx", line 372, in av.codec.context.CodecContext.decode
  File "av/video/codeccontext.pyx", line 108, in av.video.codeccontext.VideoCodecContext._decode
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 1094995529] Invalid data found when processing input (libav.h264: no frame!)
`

**Comment by koenvo** [comment]
nope. But I didn't spend time on it lately. Looks like your error is same as mine..

**Comment by adavoudi** [comment]
Some codecs need a few extra data for decoding and I think h264 is one of them. So I made a few changes to the code and provided a function to copy these data from a source CodecContext to a destination CodecContext. In my case, the data was about 40 bytes (so we can easily save it somewhere).

I sent a pull request #287. 

@mikeboers Would you please check it?

**Comment by jd20** [comment]
I've been hitting the same issue when trying to re-decode from raw packets (about no start code, and cannot split NAL units).

@adavoudi I tested your PR locally, and it fixed the problems I was having. Would be great if this could get merged.

**Comment by l0stb1t** [comment]
I am working with the tello drone which transmits raw h264 through udp socket. How do I get the extradata from the stream ?? The TelloPy library creates a file like object from recveived udp then use av.open on it which result in a very laggy stream.

**Comment by ramoncaldeira** [comment]
@l0stb1t can you get this from the container?

Example:
```
codec_ctx = container.streams.video[0].codec_context 
codec_ctx.extradata
```

**Comment by arvindchandel** [comment]
@koenvo @jd20 Hi, I want my frame to H264 encoded and then decoded back to original frame. For this i tried the above code and hitting the same issues 'Error splitting the input into NAL units'. Can you provide me any right example/pointer for my problem.

**Comment by arvindchandel** [comment]
> @koenvo Did you manage to solve the problem?
> In my case the error is as below:
> 
> `File "av/codec/context.pyx", line 326, in av.codec.context.CodecContext.decode File "av/codec/context.pyx", line 372, in av.codec.context.CodecContext.decode File "av/video/codeccontext.pyx", line 108, in av.video.codeccontext.VideoCodecContext._decode File "av/utils.pyx", line 105, in av.utils.err_check av.AVError: [Errno 1094995529] Invalid data found when processing input (libav.h264: no frame!)`

did u get solution for this.

**Comment by jlaine** [comment]
Please refrain from hijacking a closed issue. If you have found a bug in pyav please open a new issue. If it's to chat with other users consider using the project's gitter
