### ISSUE TITLE
codec-ctx decoding issue

### ISSUE THREAD

**Issue by GoelBiju** [mikeboers/PyAV#181]
Hi Mr. Boers,

Not to be persistent, though I tried at decoding an flv using the codec-ctx branch of PyAV. I set the CodecContext (stated in scratchpad/cctx_decoding.py) to flv. and opened a sample flv file. 

```python
import logging

logging.basicConfig()

import av
from av.codeccontext import CodecContext
from av.video import VideoFrame
from av.packet import Packet

cc = CodecContext.create('flv', 'r')
print cc

# fh = open('test.mp4', 'r')
fh = open('Sample.flv', 'r')

frame_count = 0

while True:
    chunk = fh.read(100)
    if not chunk:
        break

    packet = Packet(chunk)
    print packet
    assert str(buffer(packet)) == chunk

    frames = cc.decode(packet) or ()
    for frame in frames:
        print frame
        img = frame.to_image()
        img.save('sandbox/test.%04d.jpg' % frame_count)
        frame_count += 1
```

However, all that returned was an error from libav stating how the picture start code was invalid or the header was damaged:

```python
<av.VideoCodecContext video/flv at 0x7f470d5f47e0>
<av.Packet of #0, dts=None, pts=None; 128 bytes at 0x7f4711bd3890>
Traceback (most recent call last):
  File "/home/ubuntu/workspace/PyAV/scratchpad/cctx_decode.py", line 30, in <module>
    frames = cc.decode(packet) or ()
  File "av/codeccontext.pyx", line 83, in av.codeccontext.CodecContext.decode (src/av/codeccontext.c:3598)
  File "av/codeccontext.pyx", line 115, in av.codeccontext.CodecContext.decode (src/av/codeccontext.c:3331)
  File "av/video/codeccontext.pyx", line 134, in av.video.codeccontext.VideoCodecContext._decode_one (src/av/video/codeccontext.c:2109)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1517)
av.AVError: [Errno 1094995529] Invalid data found when processing input
ERROR:libav.flv:Bad picture start code
ERROR:libav.flv:header damaged
```

Is there any particular method to handling flvs? Regarding my previous question about the decoding of frames via the buffer, surely this should handle it if the codec context was setup and the packet allocated can be decoded by just using the buffer?

**Comment by mikeboers** [comment]
I just started writing that today; you get the same errors that I do at this point.

But I like your spirit! 😀

**Comment by mikeboers** [comment]
Closing this in favour of #155.
