### ISSUE TITLE
av.AVError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by crackwitz** [mikeboers/PyAV#228]
win7 x64, ffmpeg zeranoe 3.3.1 x64 shared+dev, cpython 3.6.1.

pyav built and installed as described (`setup.py install --ffmpeg-dir=...`).

when trying to run `examples\show_frames_opencv.py`, I get the following:

> Traceback (most recent call last):
>   File "P:\pyav\examples\show_frames_opencv.py", line 13, in <module>
>     for frame in packet.decode():
>   File "av\packet.pyx", line 106, in av.packet.Packet.decode (src\av\packet.c:2868)
>   File "av\stream.pyx", line 116, in av.stream.Stream.decode (src\av\stream.c:3312)
>   File "av\codec\context.pyx", line 330, in av.codec.context.CodecContext.decode (src\av\codec\context.c:6421)
>   File "av\codec\context.pyx", line 210, in av.codec.context.CodecContext._send_packet_and_recv (src\av\codec\context.c:4689)
>   File "av\codec\context.pyx", line 232, in av.codec.context.CodecContext._recv_frame (src\av\codec\context.c:4989)
>   File "av\utils.pyx", line 101, in av.utils.err_check (src\av\utils.c:2444)
> av.AVError: [Errno 11] Resource temporarily unavailable> 

(and also `TabError: inconsistent use of tabs and spaces in indentation`)

might this be an incompatibility between pyav and ffmpeg 3.3.1? do I need an older ffmpeg?

**Comment by crackwitz** [comment]
figured it out. EAGAIN can be -35 or -11, so this needs a few changes in av/codec/context.pyx

once I've figured out how to work with pull requests, I'll make one for this

**Comment by crackwitz** [comment]
fixed with 85fbff7f7664c52dbc6a1d5c08eaed10b71371a3
