### ISSUE TITLE
iteritems() is called on Python 3

### ISSUE THREAD

**Issue by vbkaisetsu** [mikeboers/PyAV#236]
In Python 3, iteritems() is removed, and items() returns an iterator.
Therefore, mux() does not work on Python 3.

I know that items() is slightly slow on Python 2, so it can't be replaced simply.

```
Traceback (most recent call last):
  File "./test.py", line 141, in <module>
    main()
  File "./test.py", line 120, in main
    new_video.mux(packet)
  File "av/container/output.pyx", line 194, in av.container.output.OutputContainer.mux (src/av/container/output.c:4058)
  File "av/container/output.pyx", line 200, in av.container.output.OutputContainer.mux_one (src/av/container/output.c:4288)
  File "av/container/output.pyx", line 161, in av.container.output.OutputContainer.start_encoding (src/av/container/output.c:3448)
AttributeError: 'Dictionary' object has no attribute 'iteritems'
```

**Comment by mikeboers** [comment]
Thanks for pointing that out. Fixed.
