### ISSUE TITLE
[pip install av] both win64 linux-x64 linux-armv7 error

### ISSUE THREAD

**Issue by liuxue0905** [mikeboers/PyAV#238]
win64
```
C:\Users\liuxue>pip install av
Collecting av
  Using cached av-0.3.3.tar.gz
Installing collected packages: av
  Running setup.py install for av ... error
    Complete output from command d:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\liuxue\\appdata\\local\\temp\\pip-build-cq6uln\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\liuxue\appdata\local\temp\pip-8nuwew-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\av
    copying av\__init__.py -> build\lib.win-amd64-2.7\av
    copying av\__main__.py -> build\lib.win-amd64-2.7\av
    creating build\lib.win-amd64-2.7\av\audio
    copying av\audio\__init__.py -> build\lib.win-amd64-2.7\av\audio
    creating build\lib.win-amd64-2.7\av\container
    copying av\container\__init__.py -> build\lib.win-amd64-2.7\av\container
    creating build\lib.win-amd64-2.7\av\filter
    copying av\filter\__init__.py -> build\lib.win-amd64-2.7\av\filter
    creating build\lib.win-amd64-2.7\av\subtitles
    copying av\subtitles\__init__.py -> build\lib.win-amd64-2.7\av\subtitles
    creating build\lib.win-amd64-2.7\av\video
    copying av\video\__init__.py -> build\lib.win-amd64-2.7\av\video
    running build_ext
    running reflect
    running config
    looking for avformat_open_input... missing
    looking for pyav_function_should_not_exist... missing
    looking for av_calloc... missing
    looking for av_frame_get_best_effort_timestamp... missing
    looking for avformat_alloc_output_context2... missing
    looking for avformat_close_input... missing
    looking for AVStream.index... missing
    looking for PyAV.struct_should_not_exist... missing
    looking for AVFrame.mb_type... missing

    We didn't find `avformat_open_input` in the libraries.
    We look for it only as a sanity check to make sure the build
    process is working as expected. It is not, so we must abort.

    Please open a ticket at https://github.com/mikeboers/PyAV/issues
    with the folowing information:

    PyAV: 0.3.3
    Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
    platform: Windows-10-10.0.15063
    extension_extra:
        libraries: ['avformat', 'avcodec', 'avdevice', 'avutil', 'avfilter', 'swscale', 'swresample']
        extra_link_args: ['/OPT:NOREF']
        library_dirs: ['d:\\python27\\libs', 'd:\\python27\\PCbuild\\amd64', 'd:\\python27\\PC\\VS9.0\\amd64']
        include_dirs: ['include', 'd:\\python27\\include', 'd:\\python27\\PC']
    config_macros:
        PYAV_VERSION=0.3.3
        PYAV_VERSION_STR="0.3.3"
        PYAV_COMMIT_STR="unknown-commit"
        inline=__inline
        PYAV_HAVE_LIBSWRESAMPLE=1

    ----------------------------------------
Command "d:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\liuxue\\appdata\\local\\temp\\pip-build-cq6uln\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\liuxue\appdata\local\temp\pip-8nuwew-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\liuxue\appdata\local\temp\pip-build-cq6uln\av\
```

ERROR:
```
Command "d:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\liuxue\\appdata\\local\\temp\\pip-build-cq6uln\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\liuxue\appdata\local\temp\pip-8nuwew-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\liuxue\appdata\local\temp\pip-build-cq6uln\av\
```

linux-armv7
```
Downloading/unpacking av
  Downloading av-0.3.3.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py (path:/tmp/pip-build-p9htsV/av/setup.py) egg_info for package av
    
Installing collected packages: av
  Running setup.py install for av
    Could not find libavformat with pkg-config.
    Could not find libavcodec with pkg-config.
    Could not find libavdevice with pkg-config.
    Could not find libavutil with pkg-config.
    Could not find libavfilter with pkg-config.
    Could not find libswscale with pkg-config.
    Could not find either libswresample or libavresample with pkg-config.
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-p9htsV/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mEDOAi-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-armv7l-2.7

creating build/lib.linux-armv7l-2.7/av

copying av/__main__.py -> build/lib.linux-armv7l-2.7/av

copying av/__init__.py -> build/lib.linux-armv7l-2.7/av

creating build/lib.linux-armv7l-2.7/av/container

copying av/container/__init__.py -> build/lib.linux-armv7l-2.7/av/container

creating build/lib.linux-armv7l-2.7/av/subtitles

copying av/subtitles/__init__.py -> build/lib.linux-armv7l-2.7/av/subtitles

creating build/lib.linux-armv7l-2.7/av/video

copying av/video/__init__.py -> build/lib.linux-armv7l-2.7/av/video

creating build/lib.linux-armv7l-2.7/av/filter

copying av/filter/__init__.py -> build/lib.linux-armv7l-2.7/av/filter

creating build/lib.linux-armv7l-2.7/av/audio

copying av/audio/__init__.py -> build/lib.linux-armv7l-2.7/av/audio

running build_ext

running reflect

running config

Could not find libavformat with pkg-config.

Could not find libavcodec with pkg-config.

Could not find libavdevice with pkg-config.

Could not find libavutil with pkg-config.

Could not find libavfilter with pkg-config.

Could not find libswscale with pkg-config.

Could not find either libswresample or libavresample with pkg-config.

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-p9htsV/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mEDOAi-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-p9htsV/av
Storing debug log for failure in /root/.pip/pip.log
```

ERROR:
```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-p9htsV/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mEDOAi-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-p9htsV/av
Storing debug log for failure in /root/.pip/pip.log
```

linux-x64
```
Downloading/unpacking av
  Downloading av-0.3.3.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py (path:/tmp/pip-build-27fWjj/av/setup.py) egg_info for package av
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-27fWjj/av/setup.py", line 48, in <module>
        git_commit, _ = Popen(['git', 'describe', '--tags'], stdout=PIPE, stderr=PIPE).communicate()
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-27fWjj/av/setup.py", line 48, in <module>

    git_commit, _ = Popen(['git', 'describe', '--tags'], stdout=PIPE, stderr=PIPE).communicate()

  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__

    errread, errwrite)

  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child

    raise child_exception

OSError: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-27fWjj/av
Storing debug log for failure in /root/.pip/pip.log
```

ERROR:
```
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-27fWjj/av
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by hhsprings** [comment]
**Unix variant**: install ffmpeg (or libav), and install pkg-config. (maybe you can do it via the package manager on your system like `dnf` (formally `yum`) on Fedora, `apt-get` on Debian, etc.)
**Windows**: I think we can't install via pip for now (maybe). First, download the both 'shared' and 'dev' of `ffmpeg`, and configure PATH environment variable, secondly, execute `setup.py` like:
```
python setup.py build --ffpmeg-dir=/path/to/your_ffmpeg_dev
python setup.py install
```

**Comment by jlaine** [comment]
Is any more work needed on this ticket?

**Comment by mikeboers** [comment]
I don't think so. The build process changed a lot and a few warnings were added.
