### ISSUE TITLE
Undefined symbol: avcodec_receive_frame

### ISSUE THREAD

**Issue by w495** [mikeboers/PyAV#249]
I have an import error when I try to build the latest revision from master (`v0.3.3-110-g5f3ffb4`)

```
(Linux.4.8.15-300.fc25.i686+PAE.cpython2.7) [w495@localhost PyAV]$ uname -a
Linux localhost.localdomain 4.8.15-300.fc25.i686+PAE #1 SMP Thu Dec 15 23:36:48 UTC 2016 i686 i686 i386 GNU/Linux
(Linux.4.8.15-300.fc25.i686+PAE.cpython2.7) [w495@localhost PyAV]$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:08:16) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import av
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame (src/av/audio/frame.c:4130)
    from av.audio.format cimport get_audio_format
  File "av/codec/codec.pxd", line 6, in init av.frame (src/av/frame.c:3538)
    cdef class Codec(object):
  File "av/codec/__init__.py", line 1, in <module>
    from .codec import Codec, codecs_available
  File "av/video/format.pxd", line 4, in init av.codec.codec (src/av/codec/codec.c:5054)
    cdef class VideoFormat(object):
  File "av/video/__init__.py", line 1, in <module>
    from .frame import VideoFrame
  File "av/container/streams.pxd", line 4, in init av.video.frame (src/av/video/frame.c:6340)
    cdef class StreamContainer(object):
  File "av/container/__init__.py", line 1, in <module>
    from .core import Container, open
  File "av/packet.pxd", line 8, in init av.container.core (src/av/container/core.c:4738)
    cdef class Packet(Buffer):
  File "av/container/streams.pxd", line 4, in init av.packet (src/av/packet.c:4298)
    cdef class StreamContainer(object):
  File "av/codec/context.pxd", line 11, in init av.container.streams (src/av/container/streams.c:4084)
    cdef class CodecContext(object):
ImportError: av/codec/context.so: undefined symbol: avcodec_receive_frame
>>> 

```

It may be helpfull, that while building i got this:
```
...
running config
looking for avformat_open_input... found
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... found
looking for avformat_close_input... found
looking for avcodec_send_packet... found
looking for AV_OPT_TYPE_INT...found
looking for PYAV_ENUM_SHOULD_NOT_EXIST...missing
looking for AV_OPT_TYPE_BOOL...found
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing
writing build/temp.linux-i686-2.7/include/pyav/config.h
running cythonize
...
```

**Comment by mikeboers** [comment]
Can you confirm what version of FFmpeg you're binding against?

**Comment by w495** [comment]
```
ffmpeg version 2.2.4
built on May 23 2015 12:25:09 with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
configuration: --enable-gpl --enable-nonfree --enable-shared --enable-pic --enable-libx264 --enable-libvpx --enable-openssl --disable-podpages --prefix=/home/dallan/anaconda/envs/_build
libavutil      52. 66.100 / 52. 66.100
libavcodec     55. 52.102 / 55. 52.102
libavformat    55. 33.100 / 55. 33.100
libavdevice    55. 10.100 / 55. 10.100
libavfilter     4.  2.100 /  4.  2.100
libswscale      2.  5.102 /  2.  5.102
libswresample   0. 18.100 /  0. 18.100
libpostproc    52.  3.100 / 52.  3.100
```

**Comment by mikeboers** [comment]
How did the check for `avcodec_send_packet` pass?!

Maybe it is building against one library and linking against another? `python -m av --version` would reveal what it built against, but you won't be able to run that directly. Maybe `python /path/to/av/__main__.py --version` will skip the import problem. Or comment out all the imports in `__init__.py`. 😛

**Comment by w495** [comment]
I've used this: https://anaconda.org/danielballan/pyav for `linux-32`
I think the problem may be in i386 (32bit)  build of ffmpeg. It is PAE box.

**Comment by jlaine** [comment]
I'd say close this issue, all FFmpegs we support feature the send / recv mechanism
