### ISSUE TITLE
OverflowError when seeking to time

### ISSUE THREAD

**Issue by mkfmnn** [mikeboers/PyAV#251]
`Container.seek` no longer supports seeking to times more than ~35 minutes into a media file, since `offset` is being converted to an `int` instead of `int64_t` as of 69602b6d24738d7b1b17976e9adcc4934b6ebf72.

```
>>> m.seek(2700 * av.time_base)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "av/container/input.pyx", line 174, in av.container.input.InputContainer.seek (src/av/container/input.c:3488)
  File "av/container/core.pyx", line 132, in av.container.core.ContainerProxy.seek (src/av/container/core.c:2678)
OverflowError: value too large to convert to int
```

**Comment by mikeboers** [comment]
Makes sense. Thanks for figuring that out so precisely.
