### ISSUE TITLE
pyav fails to decode jpg while ffmpeg works fine

### ISSUE THREAD

**Issue by zwn** [mikeboers/PyAV#264]
I am experiencing a strange error. I have images from IP camera (see attachment) that contain some extra bytes before EOI marker (0xd9).

![cam170613_180939_000](https://user-images.githubusercontent.com/1130051/29023508-3f13f774-7b6e-11e7-9248-331da955cfe8.jpg)

I can process them just fine using ffmpeg. I am using conda release that is based on ffmpeg 3.2.4.

```sh
$ ffmpeg -y -i cam170613_180939_000.jpg out.png
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-15)
  configuration: --prefix=/home/zbynek/miniconda2/envs/pyav --disable-doc --enable-shared --enable-static --extra-cflags='-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC -I/home/zbynek/miniconda2/envs/pyav/include' --extra-cxxflags='=-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC' --extra-libs='-L/home/zbynek/miniconda2/envs/pyav/lib -lz' --enable-pic --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --enable-libx264
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, image2, from 'cam170613_180939_000.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 40484 kb/s
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 2048x1536, 25 tbr, 25 tbn, 25 tbc
[swscaler @ 0x1485120] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'out.png':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: png, rgb24, 2048x1536, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.64.101 png
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> png (native))
Press [q] to stop, [?] for help
frame=    1 fps=1.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.0391x    
video:2539kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

Shows no problems.

However, I get the following problem with `decode.py`:
```
$ python ../tools/decode.py cam170613_180939_000.jpg
container: <av.InputContainer 'cam170613_180939_000.jpg'>
	format: <av.ContainerFormat 'image2'>
	duration: 0.04
	metadata:

1 stream(s):
	<av.VideoStream #0 mjpeg, yuvj422p 2048x1536 at 0x7f29142fec30>
		time_base: Fraction(1, 25)
		rate: Fraction(1, 25)
		start_time: 0
		duration: 0.040s (1/25 or 1/25)
		bit_rate: None
		bit_rate_tolerance: 4000000
		video:
			format: <av.VideoFormat yuvj422p, 2048x1536>
			average_rate: Fraction(0, 1)
		metadata:

00 <av.Packet of #0, dts=0, pts=0 at 0x7f29142fed70>
	duration: 0.040s (1/25 or 1/25)
	pts: 0.000s (0 or 0/25)
	dts: 0.000s (0 or 0/25)
Traceback (most recent call last):
  File "../tools/decode.py", line 93, in <module>
    for frame in packet.decode():
  File "av/packet.pyx", line 39, in av.packet.Packet.decode (src/av/packet.c:1856)
  File "av/stream.pyx", line 203, in av.stream.Stream.decode (src/av/stream.c:4549)
  File "av/video/stream.pyx", line 51, in av.video.stream.VideoStream._decode_one (src/av/video/stream.c:2066)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1749)
av.AVError: [Errno 1094995529] Invalid data found when processing input
CRITICAL:libav.mjpeg:No JPEG data found in image
```
where `decode.py` is from `pyav/examples`. 

The same problem is reported when I mux the .jpg files into .mkv and then run `decode.py` on the .mkv. When I pre-process the files with `jpegtran`, it fixes the problem with the extra bytes and also makes this other problem go away.

I don't have enough cython fu to debug this myself. Can anyone help? It seems like a problem in `_decode_one`.

**Comment by mikeboers** [comment]
I honestly don't know where to start. On the current HEAD, the examples work fine:

```
$ python examples/decode.py 29023508-3f13f774-7b6e-11e7-9248-331da955cfe8.jpg 
container: <av.InputContainer '29023508-3f13f774-7b6e-11e7-9248-331da955cfe8.jpg'>
	format: <av.ContainerFormat 'image2'>
	duration: 0.04
	metadata:

1 stream(s):
	<av.VideoStream #0 mjpeg, yuvj422p 2048x1536 at 0x1100c1050>
		time_base: Fraction(1, 25)
		rate: None
		start_time: 0
		duration: 0.040s (1/25 or 1/25)
		bit_rate: None
		bit_rate_tolerance: None
		video:
			format: <av.VideoFormat yuvj422p, 2048x1536>
			average_rate: None
		metadata:

00 <av.Packet of #0, dts=0, pts=0; 202421 bytes at 0x10feb46e0>
	duration: 0.040s (1/25 or 1/25)
	pts: 0.000s (0 or 0/25)
	dts: 0.000s (0 or 0/25)
	decoded: <av.VideoFrame #0, yuvj422p 2048x1536 at 0x10ff68520>
		pts: 0.000s (0 or 0/25)

01 <av.Packet of #0, dts=None, pts=None; 0 bytes at 0x10feb4788>
	duration: 0.000s (0 or 0/25)
	pts: None
	dts: None
```

And `examples/save_frames.py` makes a `sandbox/0000.jpg` as expected.

I'm testing against ffmpeg 3.2. I guess I'll go build yours...

**Comment by mikeboers** [comment]
Can you please try this with the current master?
