### ISSUE TITLE
Every file reports "cannot find cimported module 'libav'"

### ISSUE THREAD

**Issue by funkybob** [mikeboers/PyAV#283]
Recently I started migrating my requirements.txt to Pipfile instead, using pipenv... and my test servers run into this:

```
12:39:58 Collecting av
12:39:58   Downloading av-0.3.3.tar.gz (1.2MB)
12:39:59     Complete output from command python setup.py egg_info:
12:39:59     running egg_info
12:39:59     creating pip-egg-info/av.egg-info
12:39:59     writing pip-egg-info/av.egg-info/PKG-INFO
12:39:59     writing top-level names to pip-egg-info/av.egg-info/top_level.txt
12:39:59     writing dependency_links to pip-egg-info/av.egg-info/dependency_links.txt
12:39:59     writing entry points to pip-egg-info/av.egg-info/entry_points.txt
12:39:59     writing manifest file 'pip-egg-info/av.egg-info/SOURCES.txt'
12:39:59     av/stream.pyx: cannot find cimported module 'libav'
12:39:59     av/stream.pxd: cannot find cimported module 'libav'
12:39:59     ./av/frame.pxd: cannot find cimported module 'libav'
12:39:59     ./av/packet.pxd: cannot find cimported module 'libav'
12:39:59     ./av/stream.pxd: cannot find cimported module 'libav'
12:39:59     ./av/container/core.pxd: cannot find cimported module 'libav'
12:39:59     ./av/dictionary.pxd: cannot find cimported module 'libav'
12:39:59     ./av/format.pxd: cannot find cimported module 'libav'
12:39:59     ./av/utils.pxd: cannot find cimported module 'libav'
12:39:59     ./av/video/stream.pxd: cannot find cimported module 'libav'
12:39:59     ./av/video/reformatter.pxd: cannot find cimported module 'libav'
12:39:59     ./av/video/format.pxd: cannot find cimported module 'libav'
12:39:59     ./av/video/frame.pxd: cannot find cimported module 'libav'
12:39:59     ./av/audio/stream.pxd: cannot find cimported module 'libav'
12:39:59     ./av/audio/frame.pxd: cannot find cimported module 'libav'
12:39:59     ./av/audio/format.pxd: cannot find cimported module 'libav'
12:39:59     ./av/audio/resampler.pxd: cannot find cimported module 'libav'
12:39:59     ./av/audio/fifo.pxd: cannot find cimported module 'libav'
12:39:59     av/dictionary.pxd: cannot find cimported module 'libav'
12:39:59     av/packet.pyx: cannot find cimported module 'libav'
12:39:59     av/packet.pxd: cannot find cimported module 'libav'
12:39:59     av/logging.pyx: cannot find cimported module 'libav'
12:39:59     av/codec.pxd: cannot find cimported module 'libav'
12:39:59     ./av/descriptor.pxd: cannot find cimported module 'libav'
12:39:59     av/option.pyx: cannot find cimported module 'libav'
12:39:59     av/option.pxd: cannot find cimported module 'libav'
12:39:59     av/utils.pyx: cannot find cimported module 'libav'
12:39:59     av/utils.pxd: cannot find cimported module 'libav'
12:39:59     av/format.pyx: cannot find cimported module 'libav'
12:39:59     av/format.pxd: cannot find cimported module 'libav'
12:39:59     av/frame.pxd: cannot find cimported module 'libav'
12:39:59     av/descriptor.pyx: cannot find cimported module 'libav'
12:39:59     av/descriptor.pxd: cannot find cimported module 'libav'
12:39:59     ./av/option.pxd: cannot find cimported module 'libav'
12:39:59     av/_core.pyx: cannot find cimported module 'libav'
12:39:59     av/audio/stream.pxd: cannot find cimported module 'libav'
12:39:59     av/audio/fifo.pxd: cannot find cimported module 'libav'
12:39:59     av/audio/resampler.pyx: cannot find cimported module 'libav'
12:39:59     av/audio/resampler.pxd: cannot find cimported module 'libav'
12:39:59     av/audio/plane.pyx: cannot find cimported module 'libav'
12:39:59     av/audio/layout.pyx: cannot find cimported module 'libav'
12:39:59     av/audio/format.pxd: cannot find cimported module 'libav'
12:39:59     av/audio/frame.pxd: cannot find cimported module 'libav'
12:39:59     av/video/stream.pxd: cannot find cimported module 'libav'
12:39:59     av/video/reformatter.pyx: cannot find cimported module 'libav'
12:39:59     av/video/reformatter.pxd: cannot find cimported module 'libav'
12:39:59     av/video/format.pxd: cannot find cimported module 'libav'
12:39:59     av/video/frame.pxd: cannot find cimported module 'libav'
12:39:59     av/subtitles/stream.pyx: cannot find cimported module 'libav'
12:39:59     ./av/subtitles/subtitle.pxd: cannot find cimported module 'libav'
12:39:59     av/subtitles/subtitle.pxd: cannot find cimported module 'libav'
12:39:59     av/container/streams.pyx: cannot find cimported module 'libav'
12:39:59     av/container/core.pyx: cannot find cimported module 'libav'
12:39:59     av/container/core.pxd: cannot find cimported module 'libav'
12:39:59     ./av/container/output.pxd: cannot find cimported module 'libav'
12:39:59     ./av/container/input.pxd: cannot find cimported module 'libav'
12:39:59     av/container/output.pxd: cannot find cimported module 'libav'
12:39:59     av/container/input.pxd: cannot find cimported module 'libav'
12:39:59     av/filter/filter.pyx: cannot find cimported module 'libav'
12:39:59     av/filter/filter.pxd: cannot find cimported module 'libav'
12:39:59     ./av/filter/pad.pxd: cannot find cimported module 'libav'
12:39:59     ./av/filter/filter.pxd: cannot find cimported module 'libav'
12:39:59     ./av/filter/link.pxd: cannot find cimported module 'libav'
12:39:59     ./av/filter/graph.pxd: cannot find cimported module 'libav'
12:39:59     ./av/filter/context.pxd: cannot find cimported module 'libav'
12:39:59     av/filter/link.pyx: cannot find cimported module 'libav'
12:39:59     av/filter/link.pxd: cannot find cimported module 'libav'
12:39:59     av/filter/graph.pxd: cannot find cimported module 'libav'
12:39:59     av/filter/context.pxd: cannot find cimported module 'libav'
12:39:59     av/filter/pad.pxd: cannot find cimported module 'libav'
12:39:59     Compiling av/stream.pyx because it changed.
12:39:59     Compiling av/diction
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     cimport libav as lib
12:39:59            ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:1:8: 'libav.pxd' not found
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     cimport libav as lib
12:39:59     
12:39:59     # Setup base library. While the docs and experience may lead us to believe we
12:39:59     # don't need to call all of these (e.g. avcodec_register_all is usually
12:39:59     # unnessesary), some users have found contexts in which they are required.
12:39:59     lib.av_register_all()
12:39:59       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:6:3: cimported module has no attribute 'av_register_all'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     
12:39:59     # Setup base library. While the docs and experience may lead us to believe we
12:39:59     # don't need to call all of these (e.g. avcodec_register_all is usually
12:39:59     # unnessesary), some users have found contexts in which they are required.
12:39:59     lib.av_register_all()
12:39:59     lib.avformat_network_init()
12:39:59       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:7:3: cimported module has no attribute 'avformat_network_init'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     # Setup base library. While the docs and experience may lead us to believe we
12:39:59     # don't need to call all of these (e.g. avcodec_register_all is usually
12:39:59     # unnessesary), some users have found contexts in which they are required.
12:39:59     lib.av_register_all()
12:39:59     lib.avformat_network_init()
12:39:59     lib.avdevice_register_all()
12:39:59       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:8:3: cimported module has no attribute 'avdevice_register_all'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     # don't need to call all of these (e.g. avcodec_register_all is usually
12:39:59     # unnessesary), some users have found contexts in which they are required.
12:39:59     lib.av_register_all()
12:39:59     lib.avformat_network_init()
12:39:59     lib.avdevice_register_all()
12:39:59     lib.avcodec_register_all()
12:39:59       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:9:3: cimported module has no attribute 'avcodec_register_all'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     # unnessesary), some users have found contexts in which they are required.
12:39:59     lib.av_register_all()
12:39:59     lib.avformat_network_init()
12:39:59     lib.avdevice_register_all()
12:39:59     lib.avcodec_register_all()
12:39:59     lib.avfilter_register_all()
12:39:59       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:10:3: cimported module has no attribute 'avfilter_register_all'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     lib.avdevice_register_all()
12:39:59     lib.avcodec_register_all()
12:39:59     lib.avfilter_register_all()
12:39:59     
12:39:59     # Exports.
12:39:59     time_base = lib.AV_TIME_BASE
12:39:59                   ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:13:15: cimported module has no attribute 'AV_TIME_BASE'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     
12:39:59     # Exports.
12:39:59     time_base = lib.AV_TIME_BASE
12:39:59     
12:39:59     
12:39:59     pyav_version = lib.PYAV_VERSION_STR
12:39:59                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:16:18: cimported module has no attribute 'PYAV_VERSION_STR'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     # Exports.
12:39:59     time_base = lib.AV_TIME_BASE
12:39:59     
12:39:59     
12:39:59     pyav_version = lib.PYAV_VERSION_STR
12:39:59     pyav_commit = lib.PYAV_COMMIT_STR
12:39:59                     ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:17:17: cimported module has no attribute 'PYAV_COMMIT_STR'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59         cdef int micro = (v      ) & 0xff
12:39:59         return (major, minor, micro)
12:39:59     
12:39:59     versions = {
12:39:59         'libavutil': dict(
12:39:59             version=decode_version(lib.avutil_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:30:34: cimported module has no attribute 'avutil_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59         return (major, minor, micro)
12:39:59     
12:39:59     versions = {
12:39:59         'libavutil': dict(
12:39:59             version=decode_version(lib.avutil_version()),
12:39:59             configuration=lib.avutil_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:31:25: cimported module has no attribute 'avutil_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59     
12:39:59     versions = {
12:39:59         'libavutil': dict(
12:39:59             version=decode_version(lib.avutil_version()),
12:39:59             configuration=lib.avutil_configuration(),
12:39:59             license=lib.avutil_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:32:19: cimported module has no attribute 'avutil_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.avutil_version()),
12:39:59             configuration=lib.avutil_configuration(),
12:39:59             license=lib.avutil_license()
12:39:59         ),
12:39:59         'libavcodec': dict(
12:39:59             version=decode_version(lib.avcodec_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:35:34: cimported module has no attribute 'avcodec_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.avutil_configuration(),
12:39:59             license=lib.avutil_license()
12:39:59         ),
12:39:59         'libavcodec': dict(
12:39:59             version=decode_version(lib.avcodec_version()),
12:39:59             configuration=lib.avcodec_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:36:25: cimported module has no attribute 'avcodec_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.avutil_license()
12:39:59         ),
12:39:59         'libavcodec': dict(
12:39:59             version=decode_version(lib.avcodec_version()),
12:39:59             configuration=lib.avcodec_configuration(),
12:39:59             license=lib.avcodec_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:37:19: cimported module has no attribute 'avcodec_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.avcodec_version()),
12:39:59             configuration=lib.avcodec_configuration(),
12:39:59             license=lib.avcodec_license()
12:39:59         ),
12:39:59         'libavformat': dict(
12:39:59             version=decode_version(lib.avformat_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:40:34: cimported module has no attribute 'avformat_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.avcodec_configuration(),
12:39:59             license=lib.avcodec_license()
12:39:59         ),
12:39:59         'libavformat': dict(
12:39:59             version=decode_version(lib.avformat_version()),
12:39:59             configuration=lib.avformat_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:41:25: cimported module has no attribute 'avformat_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.avcodec_license()
12:39:59         ),
12:39:59         'libavformat': dict(
12:39:59             version=decode_version(lib.avformat_version()),
12:39:59             configuration=lib.avformat_configuration(),
12:39:59             license=lib.avformat_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:42:19: cimported module has no attribute 'avformat_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.avformat_version()),
12:39:59             configuration=lib.avformat_configuration(),
12:39:59             license=lib.avformat_license()
12:39:59         ),
12:39:59         'libavdevice': dict(
12:39:59             version=decode_version(lib.avdevice_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:45:34: cimported module has no attribute 'avdevice_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.avformat_configuration(),
12:39:59             license=lib.avformat_license()
12:39:59         ),
12:39:59         'libavdevice': dict(
12:39:59             version=decode_version(lib.avdevice_version()),
12:39:59             configuration=lib.avdevice_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:46:25: cimported module has no attribute 'avdevice_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.avformat_license()
12:39:59         ),
12:39:59         'libavdevice': dict(
12:39:59             version=decode_version(lib.avdevice_version()),
12:39:59             configuration=lib.avdevice_configuration(),
12:39:59             license=lib.avdevice_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:47:19: cimported module has no attribute 'avdevice_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.avdevice_version()),
12:39:59             configuration=lib.avdevice_configuration(),
12:39:59             license=lib.avdevice_license()
12:39:59         ),
12:39:59         'libavfilter': dict(
12:39:59             version=decode_version(lib.avfilter_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:50:34: cimported module has no attribute 'avfilter_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.avdevice_configuration(),
12:39:59             license=lib.avdevice_license()
12:39:59         ),
12:39:59         'libavfilter': dict(
12:39:59             version=decode_version(lib.avfilter_version()),
12:39:59             configuration=lib.avfilter_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:51:25: cimported module has no attribute 'avfilter_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.avdevice_license()
12:39:59         ),
12:39:59         'libavfilter': dict(
12:39:59             version=decode_version(lib.avfilter_version()),
12:39:59             configuration=lib.avfilter_configuration(),
12:39:59             license=lib.avfilter_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:52:19: cimported module has no attribute 'avfilter_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.avfilter_version()),
12:39:59             configuration=lib.avfilter_configuration(),
12:39:59             license=lib.avfilter_license()
12:39:59         ),
12:39:59         'libavresample': dict(
12:39:59             version=decode_version(lib.avresample_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:55:34: cimported module has no attribute 'avresample_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.avfilter_configuration(),
12:39:59             license=lib.avfilter_license()
12:39:59         ),
12:39:59         'libavresample': dict(
12:39:59             version=decode_version(lib.avresample_version()),
12:39:59             configuration=lib.avresample_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:56:25: cimported module has no attribute 'avresample_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.avfilter_license()
12:39:59         ),
12:39:59         'libavresample': dict(
12:39:59             version=decode_version(lib.avresample_version()),
12:39:59             configuration=lib.avresample_configuration(),
12:39:59             license=lib.avresample_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:57:19: cimported module has no attribute 'avresample_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.avresample_version()),
12:39:59             configuration=lib.avresample_configuration(),
12:39:59             license=lib.avresample_license()
12:39:59         ),
12:39:59         'libswscale': dict(
12:39:59             version=decode_version(lib.swscale_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:60:34: cimported module has no attribute 'swscale_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.avresample_configuration(),
12:39:59             license=lib.avresample_license()
12:39:59         ),
12:39:59         'libswscale': dict(
12:39:59             version=decode_version(lib.swscale_version()),
12:39:59             configuration=lib.swscale_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:61:25: cimported module has no attribute 'swscale_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.avresample_license()
12:39:59         ),
12:39:59         'libswscale': dict(
12:39:59             version=decode_version(lib.swscale_version()),
12:39:59             configuration=lib.swscale_configuration(),
12:39:59             license=lib.swscale_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:62:19: cimported module has no attribute 'swscale_license'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             version=decode_version(lib.swscale_version()),
12:39:59             configuration=lib.swscale_configuration(),
12:39:59             license=lib.swscale_license()
12:39:59         ),
12:39:59         'libswresample': dict(
12:39:59             version=decode_version(lib.swresample_version()),
12:39:59                                      ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:65:34: cimported module has no attribute 'swresample_version'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             configuration=lib.swscale_configuration(),
12:39:59             license=lib.swscale_license()
12:39:59         ),
12:39:59         'libswresample': dict(
12:39:59             version=decode_version(lib.swresample_version()),
12:39:59             configuration=lib.swresample_configuration(),
12:39:59                             ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:66:25: cimported module has no attribute 'swresample_configuration'
12:39:59     
12:39:59     Error compiling Cython file:
12:39:59     ------------------------------------------------------------
12:39:59     ...
12:39:59             license=lib.swscale_license()
12:39:59         ),
12:39:59         'libswresample': dict(
12:39:59             version=decode_version(lib.swresample_version()),
12:39:59             configuration=lib.swresample_configuration(),
12:39:59             license=lib.swresample_license()
12:39:59                       ^
12:39:59     ------------------------------------------------------------
12:39:59     
12:39:59     av/_core.pyx:67:19: cimported module has no attribute 'swresample_license'
12:39:59     ary.pyx because it changed.
12:39:59     Compiling av/packet.pyx because it changed.
12:39:59     Compiling av/logging.pyx because it changed.
12:39:59     Compiling av/codec.pyx because it changed.
12:39:59     Compiling av/option.pyx because it changed.
12:39:59     Compiling av/plane.pyx because it changed.
12:39:59     Compiling av/utils.pyx because it changed.
12:39:59     Compiling av/format.pyx because it changed.
12:39:59     Compiling av/buffer.pyx because it changed.
12:39:59     Compiling av/frame.pyx because it changed.
12:39:59     Compiling av/bytesource.pyx because it changed.
12:39:59     Compiling av/descriptor.pyx because it changed.
12:39:59     Compiling av/_core.pyx because it changed.
12:39:59     Compiling av/audio/stream.pyx because it changed.
12:39:59     Compiling av/audio/fifo.pyx because it changed.
12:39:59     Compiling av/audio/resampler.pyx because it changed.
12:39:59     Compiling av/audio/plane.pyx because it changed.
12:39:59     Compiling av/audio/layout.pyx because it changed.
12:39:59     Compiling av/audio/format.pyx because it changed.
12:39:59     Compiling av/audio/frame.pyx because it changed.
12:39:59     Compiling av/video/stream.pyx because it changed.
12:39:59     Compiling av/video/reformatter.pyx because it changed.
12:39:59     Compiling av/video/plane.pyx because it changed.
12:39:59     Compiling av/video/format.pyx because it changed.
12:39:59     Compiling av/video/frame.pyx because it changed.
12:39:59     Compiling av/subtitles/stream.pyx because it changed.
12:39:59     Compiling av/subtitles/subtitle.pyx because it changed.
12:39:59     Compiling av/container/streams.pyx because it changed.
12:39:59     Compiling av/container/core.pyx because it changed.
12:39:59     Compiling av/container/output.pyx because it changed.
12:39:59     Compiling av/container/input.pyx because it changed.
12:39:59     Compiling av/filter/filter.pyx because it changed.
12:39:59     Compiling av/filter/link.pyx because it changed.
12:39:59     Compiling av/filter/graph.pyx because it changed.
12:39:59     Compiling av/filter/context.pyx because it changed.
12:39:59     Compiling av/filter/pad.pyx because it changed.
12:39:59     [ 1/37] Cythonizing av/_core.pyx
12:39:59     Traceback (most recent call last):
12:39:59       File "<string>", line 1, in <module>
12:39:59       File "/tmp/pip-build-mGRVJt/av/setup.py", line 746, in <module>
12:39:59         distclass=distclass,
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
12:39:59         return distutils.core.setup(**attrs)
12:39:59       File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
12:39:59         dist.run_commands()
12:39:59       File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
12:39:59         self.run_command(cmd)
12:39:59       File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
12:39:59         cmd_obj.run()
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 278, in run
12:39:59         self.find_sources()
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
12:39:59         mm.run()
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 524, in run
12:39:59         self.add_defaults()
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
12:39:59         sdist.add_defaults(self)
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
12:39:59         self._add_defaults_ext()
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
12:39:59         build_ext = self.get_finalized_command('build_ext')
12:39:59       File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
12:39:59         cmd_obj.ensure_finalized()
12:39:59       File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
12:39:59         self.finalize_options()
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 133, in finalize_options
12:39:59         _build_ext.finalize_options(self)
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options
12:39:59         self.distribution.ext_modules)
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
12:39:59         cythonize_one(*args)
12:39:59       File "/var/lib/virtualenv/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1161, in cythonize_one
12:39:59         raise CompileError(None, pyx_file)
12:39:59     Cython.Compiler.Errors.CompileError: av/_core.pyx
12:39:59     
12:39:59     ----------------------------------------
12:39:59 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mGRVJt/av/
```

Even when I pip install with FFMPEG_DIR specified... it still barfs.

Curiously, if I revert to Cython 0.24 it works fine.

**Comment by mikeboers** [comment]
That is wacky. I wonder if the source distribution should not include the Cython.

**Comment by papr** [comment]
I have the same issue on all Cython versions >= 0.26. Ubuntu 17.10, Python 3.6.3, pip 10.0.0

**Comment by Mekk** [comment]
I feel that instead of 
```
cimport libav as lib
```
it would be proper for current cython to
```
cimport .libav as lib
```

If that causes some issues on older cythons, one could workaround by just adding this "av" directory to include_path in cythonize call (replace include_path=ext.include_dirs with include_path=ext.include_dirs + ["av"] or sth similar)

**Comment by jlaine** [comment]
Could you please check whether this is still relevant with PyAV 6.0.0?

**Comment by mikeboers** [comment]
I'm going to assume this was fixed in the great build refactor. Someone please feel free to open this back up or re-post if PyAV >= 6.0.0 doesn't fix it.
