### ISSUE TITLE
AVError when try to write to y4m file 

### ISSUE THREAD

**Issue by huiyiqun** [mikeboers/PyAV#328]
I'd like to dump the video to a lossless format. So I use [y4m](https://wiki.multimedia.cx/index.php/YUV4MPEG2).

When I mux the first frame, it fails with following errors:

```
Traceback (most recent call last):
  File "embed.py", line 191, in <module>
Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
ERROR: Codec not supported.
    main()
  File "embed.py", line 164, in main
    encode_frame(set_picture(frame, picture), video_stream)
  File "embed.py", line 117, in encode_frame
    output_container.mux(output_pkt)
  File "av/container/output.pyx", line 199, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 202, in av.container.output.OutputContainer.mux_one
  File "av/container/output.pyx", line 152, in av.container.output.OutputContainer.start_encoding
  File "av/container/core.pyx", line 182, in av.container.core.ContainerProxy.err_check
  File "av/utils.pyx", line 103, in av.utils.err_check
av.AVError: [Errno 1094995529] Invalid data found when processing input: '/tmp/output.y4m' (libav.yuv4mpegpipe: ERROR: Codec not supported.)
```

**Comment by huiyiqun** [comment]
fixed by using a codec of `wrapped_avframe`.
