### ISSUE TITLE
cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_packet_clone

### ISSUE THREAD

**Issue by General-Ilya** [mikeboers/PyAV#348]
Ubuntu 16.04, Python 3.6.5, try to import av and get the message:
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import av
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ilya/anaconda3/lib/python3.6/site-packages/av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "/home/ilya/anaconda3/lib/python3.6/site-packages/av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame
  File "av/codec/codec.pxd", line 6, in init av.frame
  File "/home/ilya/anaconda3/lib/python3.6/site-packages/av/codec/__init__.py", line 1, in <module>
    from .codec import Codec, codecs_available, codec_descriptor
  File "av/video/format.pxd", line 4, in init av.codec.codec
  File "/home/ilya/anaconda3/lib/python3.6/site-packages/av/video/__init__.py", line 1, in <module>
    from .frame import VideoFrame
  File "av/container/streams.pxd", line 4, in init av.video.frame
  File "/home/ilya/anaconda3/lib/python3.6/site-packages/av/container/__init__.py", line 1, in <module>
    from .core import Container, open
  File "av/container/output.pxd", line 8, in init av.container.core
ImportError: /home/ilya/anaconda3/lib/python3.6/site-packages/av/container/output.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_packet_clone

**Comment by General-Ilya** [comment]
It went away when I built ffmpeg 2.8.15 from source
