### ISSUE TITLE
Symbol not found: _av_codec_iterate

### ISSUE THREAD

**Issue by oblogic7** [mikeboers/PyAV#501]
Having trouble getting av to work.  I have ffmpeg 4.1.2 installed via homebrew and no errors on `pip install av==6.1.2`.  However, I get the following errors below when trying to use av in Home Assistant.  Any ideas what I should do to resolve the missing symbol issue?

```
Exception in thread stream_worker:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matt/PycharmProjects/home-assistant/homeassistant/components/stream/worker.py", line 49, in stream_worker
    import av
  File "/Users/matt/PycharmProjects/home-assistant/venv/lib/python3.5/site-packages/av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "/Users/matt/PycharmProjects/home-assistant/venv/lib/python3.5/site-packages/av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame
  File "av/codec/codec.pxd", line 4, in init av.frame
  File "/Users/matt/PycharmProjects/home-assistant/venv/lib/python3.5/site-packages/av/codec/__init__.py", line 1, in <module>
    from .codec import Codec, codecs_available, codec_descriptor
ImportError: dlopen(/Users/matt/PycharmProjects/home-assistant/venv/lib/python3.5/site-packages/av/codec/codec.cpython-35m-darwin.so, 2): Symbol not found: _av_codec_iterate
  Referenced from: /Users/matt/PycharmProjects/home-assistant/venv/lib/python3.5/site-packages/av/codec/codec.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/matt/PycharmProjects/home-assistant/venv/lib/python3.5/site-packages/av/codec/codec.cpython-35m-darwin.so
```

ffmpeg version output:
```
ffmpeg version 4.1.2 Copyright (c) 2000-2019 the FFmpeg developers
built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100

**Comment by jlaine** [comment]
It looks like you have built PyAV against modern ffmpeg libraries but are attempting to run it against an older library version. Most likely your "new" ffmpeg libraries (libav*) are in a location not picked up by the dynamic linker so you will need to set `DYLD_LIBRARY_PATH` to help it find them.

**Comment by jlaine** [comment]
No response from submitter, closing.
