### ISSUE TITLE
ubuntu arm64,  cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by hemml** [mikeboers/PyAV#505]
On Ubuntu bionic on arm64 I have got the following error on latest version of PyAV:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import av._core
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import av
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/PyAV/av/__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

$ uname -a
Linux alarm 4.19.25-sunxi64 #5.78 SMP Mon Apr 8 07:19:19 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by hemml** [comment]
I have recompiled all the libraries from source and now it works.
But the default installation way "pip3 install" don't work on Ubuntu/arm64.

**Comment by jlaine** [comment]
Unfortunately this doesn't look like a problem with pyav itself, but more like a problem at the distribution level or in ffmpeg itself..

**Comment by yuanzhedong** [comment]
I have the same issue with `pip3 install`, will try to compile from source and see...

**Comment by jlaine** [comment]
OK in that case I'm going to close this issue.
