### ISSUE TITLE
remux example fails

### ISSUE THREAD

**Issue by ilteroi** [mikeboers/PyAV#96]
hi,

i was very excited to find this project as it would really make ffmpeg more accessible ... so thanks.

tried it immediately but unfortunately, i didn't get far:

$ python remux.py video.mp4 test.mp4
00 <av.Packet of #0, dts=0, pts=0 at 0x7f8cbb1e0050>
	in:  <av.AudioStream #0 aac at 44100Hz, stereo, fltp at 0x7f8cae9ca3e0>
	out: <av.AudioStream #0 aac at 44100Hz, stereo, fltp at 0x7f8cae9ca478>
Traceback (most recent call last):
  File "remux.py", line 67, in <module>
    output.mux(packet)
  File "container.pyx", line 369, in av.container.OutputContainer.mux (src/av/container.c:5694)
  File "container.pyx", line 345, in av.container.OutputContainer.start_encoding (src/av/container.c:5368)
  File "utils.pyx", line 31, in av.utils.err_check (src/av/utils.c:1044)
av.AVError: [Errno 22] Invalid argument
ERROR:libav.mp4:Aspect ratio mismatch between muxer (0/1) and encoder layer (1/1)

same happens if i exclude audio:

$ python remux.py -a video.mp4 test.mp4
00 <av.Packet of #1, dts=0, pts=0 at 0x7f10a3bf5050>
	in:  <av.VideoStream #1 h264, yuv420p 480x360 at 0x7f10973b8050>
	out: <av.VideoStream #0 h264, yuv420p 480x360 at 0x7f10973b8230>
Traceback (most recent call last):
  File "remux.py", line 67, in <module>
    output.mux(packet)
  File "container.pyx", line 369, in av.container.OutputContainer.mux (src/av/container.c:5694)
  File "container.pyx", line 345, in av.container.OutputContainer.start_encoding (src/av/container.c:5368)
  File "utils.pyx", line 31, in av.utils.err_check (src/av/utils.c:1044)
av.AVError: [Errno 22] Invalid argument
ERROR:libav.mp4:Aspect ratio mismatch between muxer (0/1) and encoder layer (1/1)

this is with the pip version 0.2.2. can provide the video, but it's standard h.264/aac

any idea what's going wrong here?

**Comment by mikeboers** [comment]
Heh. Yeah I know what is going on her; that script should not be labeled an "example", but merely something that we are working on that is known to not work.

Sorry to get your hopes up about that one; it turned out to be a lot harder than I thought.

I'll move it so that it doesn't introduce more confusion.
